export const GET_INPUT_VALUE = 'GET_INPUT_VALUE';
export const GET_HISTORY_VALUE = 'GET_HISTORY_VALUE';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const RELOAD_HISTORY='RELOAD_HISTORY';
